name: Build Extensions

on:
  push:
    branches: [main]
    tags-ignore:
      - '**'
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: windows-latest
    env:
      NUGET_PACKAGES: ${{ github.workspace }}/.nuget/packages
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Build
        run: |
          dotnet build --configuration Release -p:GenerateAppxPackageOnBuild=true -p:Platform=x64
          dotnet build --configuration Release -p:GenerateAppxPackageOnBuild=true -p:Platform=arm64